config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :task_activities
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'task_activities#index'
end

app/models/task_activity.rb
class TaskActivity < ApplicationRecord
  belongs_to :user
end

app/controllers/task_activities_controller.rb
class TaskActivitiesController < ApplicationController
  before_action :set_task_activity, only: %i[show edit update destroy]
  # GET /task_activities or /task_activities.json
  def index
    @task_activities = TaskActivity.all
  end

  # GET /task_activities/1 or /task_activities/1.json
  def show
    @task_activity = TaskActivity.find(params[:id])
  end

  # GET /task_activities/new
  def new
    @task_activity = TaskActivity.new
  end

  # POST /task_activities or /task_activities.json
  def create
    @task_activity = TaskActivity.new(task_activity_params)

    respond_to do |format|
      if @task_activity.save
        format.html { redirect_to task_activity_url(@task_activity), notice: 'Task activity was successfully created.' }
        format.json { render :show, status: :created, location: @task_activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_activities/1 or /task_activities/1.json
  def update
    respond_to do |format|
      if @task_activity.update(task_activity_params)
        format.html { redirect_to task_activity_url(@task_activity), notice: 'Task activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_activities/1 or /task_activities/1.json
  def destroy
    @task_activity.destroy
    respond_to do |format|
      format.html { redirect_to task_activities_url, notice: 'Task activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task_activity
    @task_activity = TaskActivity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_activity_params
    params.require(:task_activity).permit(:title, :description, :completed)
  end
end

app/helpers/task_activities_helper.rb
module TaskActivitiesHelper
end

app/views/task_activities/_form.html.erb
<%= form_with(model: task_activity) do |form| %>
  <% if task_activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task_activity.errors.count, "error") %> prohibited this task_activity from being saved:</h2>

      <ul>
        <% task_activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-2 mb-2">
  <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div class="mt-2 mb-2">
  <%= form.label :description, style: "display: block" %>
  <%= form.text_area :description %>
  </div>

  <div class="mt-2 mb-2">
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>

  <div class="mt-2 mb-2">
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/task_activities/_task_activity.html.erb
<div id="<%= dom_id task_activity %>">
  <div class="card-header" style="background-color: #cbcef4; border-color: #cbcef4;">
    <h3 class="mt-2"><%= task_activity.title %></h3>

  </div>
  <div class="card-body">
    <p class="lead"><%= task_activity.description %></p>
  </div>

  <div class="card-footer" style="background-color: #f8f8f8; border-color: #f8f8f8;">
    <strong>Completed:</strong>
    <%= task_activity.completed %>
</div>
</div>

app/views/task_activities/edit.html.erb
<div class="container mt-4 mb-4">
<h1>Editing task activity</h1>

<%= render "form", task_activity: @task_activity %>

<br>

  <%= link_to "Show this task activity", @task_activity %> |
  <%= link_to "Back to task activities", task_activities_path %>
</div>

app/views/task_activities/index.html.erb
<div class="row mt-4 mb-4">
<p style="color: green"><%= notice %></p>

<h1 class="mb-4">Task Activities</h1>

<div id="task_activities">
  <% @task_activities.each do |task_activity| %>
    <%= render task_activity %>
    <p>
      <%= link_to "Show this Task", task_activity, class:"btn btn-success btn-sm" %>
    </p>
  <% end %>
</div>
</div>

<%= link_to "New Task Activity", new_task_activity_path, class: "btn btn-warning btn-lg mb-4" %>

app/views/task_activities/new.html.erb
<div class="row mt-4">
<h1>New task activity</h1>

<%= render "form", task_activity: @task_activity %>

<br>
</div>
<div>
  <%= link_to "Back to task activities", task_activities_path %>
</div>

app/views/task_activities/show.html.erb
<div class="row mt-4">
<p style="color: green"><%= notice %></p>

<%= render @task_activity %>
</div>
<div class="mt-2 mb-2">
  <%= link_to "Back", task_activities_path, class: "btn-warning btn-sm" %> |
  <%= link_to "Edit Task", edit_task_activity_path(@task_activity), class: "btn-primary btn-sm" %>

</div>
<div class="mt-2 mb-2">
  <%= link_to "Destroy Task", @task_activity, method: :delete,  class: 'btn btn-danger' %>
</div>